src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChambreRepository::class)
 */
class Chambre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $type_chambre;

   

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $disponibilite;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $accepte_animaux;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2)
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $detail;

    /**
     * @ORM\Column(type="integer")
     */
    private $num_chambre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="chambre")
     */
    private $reservations;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeChambre(): ?string
    {
        return $this->type_chambre;
    }

    public function setTypeChambre(string $type_chambre): self
    {
        $this->type_chambre = $type_chambre;

        return $this;
    }



    public function getDisponibilite(): ?string
    {
        return $this->disponibilite;
    }

    public function setDisponibilite(string $disponibilite): self
    {
        $this->disponibilite = $disponibilite;

        return $this;
    }

    public function getAccepteAnimaux(): ?string
    {
        return $this->accepte_animaux;
    }

    public function setAccepteAnimaux(string $accepte_animaux): self
    {
        $this->accepte_animaux = $accepte_animaux;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): self
    {
        $this->detail = $detail;

        return $this;
    }

    public function getNumChambre(): ?int
    {
        return $this->num_chambre;
    }

    public function setNumChambre(int $num_chambre): self
    {
        $this->num_chambre = $num_chambre;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setChambre($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getChambre() === $this) {
                $reservation->setChambre(null);
            }
        }

        return $this;
    }
}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_arrivee;

    /**
     * @ORM\Column(type="date")
     */
    private $date_depart;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nombre_animaux;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $type_animaux;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_personnes;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nombre_enfants;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity=Chambre::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $chambre;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateArrivee(): ?\DateTimeInterface
    {
        return $this->date_arrivee;
    }

    public function setDateArrivee(\DateTimeInterface $date_arrivee): self
    {
        $this->date_arrivee = $date_arrivee;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTimeInterface $date_depart): self
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getNombreAnimaux(): ?int
    {
        return $this->nombre_animaux;
    }

    public function setNombreAnimaux(?int $nombre_animaux): self
    {
        $this->nombre_animaux = $nombre_animaux;

        return $this;
    }

    public function getTypeAnimaux(): ?string
    {
        return $this->type_animaux;
    }

    public function setTypeAnimaux(?string $type_animaux): self
    {
        $this->type_animaux = $type_animaux;

        return $this;
    }

    public function getNombrePersonnes(): ?int
    {
        return $this->nombre_personnes;
    }

    public function setNombrePersonnes(int $nombre_personnes): self
    {
        $this->nombre_personnes = $nombre_personnes;

        return $this;
    }

    public function getNombreEnfants(): ?int
    {
        return $this->nombre_enfants;
    }

    public function setNombreEnfants(?int $nombre_enfants): self
    {
        $this->nombre_enfants = $nombre_enfants;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getChambre(): ?Chambre
    {
        return $this->chambre;
    }

    public function setChambre(?Chambre $chambre): self
    {
        $this->chambre = $chambre;

        return $this;
    }



}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Chambre;
use App\Entity\Client;
use App\Entity\Reservation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\MakerBundle\Doctrine\EntityRelation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType as TypeDateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_arrivee')
            ->add('date_depart')
            ->add('nombre_animaux')
            ->add('type_animaux')
            ->add('nombre_personnes')
            ->add('nombre_enfants')
            ->add('client', EntityType::class, [
                "class"=> Client::class,
                "choice_label" => "email"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface as EntityManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/reservation')]
class ReservationController extends AbstractController
{
    #[Route('/', name: 'reservation_index', methods: ['GET'])]
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }



    #[Route('/{id}', name: 'reservation_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id}/edit', name: 'reservation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'reservation_delete', methods: ['POST'])]
    public function delete(Request $request, Reservation $reservation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservation_index', [], Response::HTTP_SEE_OTHER);
    }

   

}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btnDelete">Effacer</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer une Réservation{% endblock %}

{% block body %}
    <h1>Editer une Réservation</h1>

    <a href="{{ path('reservation_index') }}"><i class="fas fa-undo-alt" id="return"></i></a>

    {{ include('reservation/_form.html.twig', {'button_label': 'Modifier'}) }}
    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation index{% endblock %}

{% block body %}
    <h1>Liste des Réservations</h1>
    <div class="trait"></div>
    <a href="{{ path('reservation_new') }}"><button>Créer</button></a>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date d'arrivée</th>
                <th>Date du départ</th>
                <th>Nombre d'animaux</th>
                <th>Type d'animaux</th>
                <th>Nombre de personnes</th>
                <th>Chambre</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.dateArrivee ? reservation.dateArrivee|date('d/m/Y') : '' }}</td>
                <td>{{ reservation.dateDepart ? reservation.dateDepart|date('d/m/Y') : '' }}</td>
                <td>{{ reservation.nombreAnimaux }}</td>
                <td>{{ reservation.typeAnimaux }}</td>
                <td>{{ reservation.nombrePersonnes }}</td>
                <td>{{ reservation.chambre.typeChambre }}</td>
                
                <td>
                    <a href="{{ path('reservation_show', {'id': reservation.id}) }}"><i class="fas fa-eye"></i></a>
                    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}"><i class="fas fa-pencil-alt"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Réservation{% endblock %}

{% block body %}
    <h1>Créer une nouvelle réservation</h1>
    <div class"trait"></div>
    <a href="{{ path('reservation_index') }}">Retour à la liste</a>

    {{ include('reservation/_form.html.twig') }}

{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation{% endblock %}

{% block body %}
    <h1>Voir la Réservation</h1>
    <div class"trait"></div>
        <a href="{{ path('reservation_index') }}"><i class="fas fa-undo-alt" id="return"></i></a>


    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}"><button class="btnModif">Modifier</button></a>

    

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Date d'arrivée</th>
                <td>{{ reservation.dateArrivee ? reservation.dateArrivee|date('d/m/Y') : '' }}</td>
            </tr>
            <tr>
                <th>Date du départ</th>
                <td>{{ reservation.dateDepart ? reservation.dateDepart|date('d/m/Y') : '' }}</td>
            </tr>
            <tr>
                <th>Nombre d'animaux</th>
                <td>{{ reservation.nombreAnimaux }}</td>
            </tr>
            <tr>
                <th>Type d'animaux</th>
                <td>{{ reservation.typeAnimaux }}</td>
            </tr>
            <tr>
                <th>Nombre de personnes</th>
                <td>{{ reservation.nombrePersonnes }}</td>
            </tr>
            <tr>
                <th>Nombre d'enfants</th>
                <td>{{ reservation.nombreEnfants }}</td>
            </tr>
        </tbody>
    </table>

{{ include('reservation/_delete_form.html.twig') }}

{% endblock %}