src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChambreRepository::class)
 */
class Chambre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $type_chambre;

   

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $disponibilite;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $accepte_animaux;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2)
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $detail;

    /**
     * @ORM\Column(type="integer")
     */
    private $num_chambre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="chambre")
     */
    private $reservations;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeChambre(): ?string
    {
        return $this->type_chambre;
    }

    public function setTypeChambre(string $type_chambre): self
    {
        $this->type_chambre = $type_chambre;

        return $this;
    }



    public function getDisponibilite(): ?string
    {
        return $this->disponibilite;
    }

    public function setDisponibilite(string $disponibilite): self
    {
        $this->disponibilite = $disponibilite;

        return $this;
    }

    public function getAccepteAnimaux(): ?string
    {
        return $this->accepte_animaux;
    }

    public function setAccepteAnimaux(string $accepte_animaux): self
    {
        $this->accepte_animaux = $accepte_animaux;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): self
    {
        $this->detail = $detail;

        return $this;
    }

    public function getNumChambre(): ?int
    {
        return $this->num_chambre;
    }

    public function setNumChambre(int $num_chambre): self
    {
        $this->num_chambre = $num_chambre;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setChambre($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getChambre() === $this) {
                $reservation->setChambre(null);
            }
        }

        return $this;
    }
}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_arrivee;

    /**
     * @ORM\Column(type="date")
     */
    private $date_depart;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nombre_animaux;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $type_animaux;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_personnes;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nombre_enfants;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity=Chambre::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $chambre;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateArrivee(): ?\DateTimeInterface
    {
        return $this->date_arrivee;
    }

    public function setDateArrivee(\DateTimeInterface $date_arrivee): self
    {
        $this->date_arrivee = $date_arrivee;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTimeInterface $date_depart): self
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getNombreAnimaux(): ?int
    {
        return $this->nombre_animaux;
    }

    public function setNombreAnimaux(?int $nombre_animaux): self
    {
        $this->nombre_animaux = $nombre_animaux;

        return $this;
    }

    public function getTypeAnimaux(): ?string
    {
        return $this->type_animaux;
    }

    public function setTypeAnimaux(?string $type_animaux): self
    {
        $this->type_animaux = $type_animaux;

        return $this;
    }

    public function getNombrePersonnes(): ?int
    {
        return $this->nombre_personnes;
    }

    public function setNombrePersonnes(int $nombre_personnes): self
    {
        $this->nombre_personnes = $nombre_personnes;

        return $this;
    }

    public function getNombreEnfants(): ?int
    {
        return $this->nombre_enfants;
    }

    public function setNombreEnfants(?int $nombre_enfants): self
    {
        $this->nombre_enfants = $nombre_enfants;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getChambre(): ?Chambre
    {
        return $this->chambre;
    }

    public function setChambre(?Chambre $chambre): self
    {
        $this->chambre = $chambre;

        return $this;
    }



}

src/Form/ResaClientType.php
<?php

namespace App\Form;

use App\Entity\Chambre;
use App\Entity\Reservation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\RadioType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ResaClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_arrivee', DateType::class, [
                "widget" => "single_text",
                "label" => "arrivée",
            ])
            ->add('date_depart',  DateType::class, [
                "widget" => "single_text",
                "label" => "depart",
            ])
            ->add('nombre_animaux')
            ->add('type_animaux', ChoiceType::class, [
                'choices' => [
                    'Aucun'=> 'Aucun','Chien'=> 'Chien','Chat' => 'Chat', 'les deux' => 'Les deux',
                ],
                "expanded" => false,
                "multiple" => false,

            ])
            ->add('nombre_personnes')
            ->add('chambre', EntityType::class, [
                "class" => Chambre::class,
                "choice_label" => function(Chambre $chambre){
                    return $chambre->getTypeChambre();
                }
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
            

        ]);
    }
}

src/Controller/ResaClientController.php
<?php

namespace App\Controller;

use App\Entity\Chambre;
use App\Entity\Client;
use App\Entity\Reservation;
use App\Form\ResaClientType;
use App\Repository\ChambreRepository;
use App\Repository\ClientRepository;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/client/login')]

class ResaClientController extends AbstractController
{
    #[Route('/resa/client/{id}', name: 'resa_client')]
    public function index( Reservation $reservation ): Response
    {   
        return $this->render('resa_client/index.html.twig', [ "reservation" => $reservation
        ]);
    }

    #[Route('/resa/nouvelle/', name: 'reservation_new', methods: ['GET', 'POST'])]
    public function new( Request $request, EntityManagerInterface $entityManager, ChambreRepository $cr, ReservationRepository $rf): Response
    {   

        $reservation = new Reservation();
        $reservation->setClient( $this->getUser());
        $form = $this->createForm(ResaClientType::class, $reservation);
        $form->handleRequest($request);
        

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservation);
            $entityManager->flush();
           
            
            $this->addFlash("success","Le Novachidine vous remercie pour votre réservation, voici le détail de votre séjour");
            return $this->redirectToRoute('resa_client', [ "id" => $reservation->getId() ], Response::HTTP_SEE_OTHER);

        }

        return $this->renderForm('resa_client/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
            'chambres' => $cr->findAll(),
            "reservationsfaites" => $rf->reservationsfaites()

            

        ]);
    }

}

templates/resa_client/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
{{ parent() }}
<link rel="stylesheet" href="{{ asset('asset/css/detailsresa.css') }}">
{% endblock %}

{% block javascripts %}
{{ parent() }}
    <script src="{{ asset('asset/js/detailResa.js') }}"></script>
{% endblock %}


{% block title %}Réservation{% endblock %}

{% block body %}
<h1>Détails de votre réservation</h1>
<div class="trait"></div>
 

      <form>
            <input id="impression" name="impression" type="button" onclick="imprimer_page()" value="Enregistrer mon détail" />
        </form>

        <h2>{{ app.user.nom}} {{app.user.prenom}}</h2><br><br>



        <div class="message">
        {% for messages in app.flashes %}
            {% for msg in messages %}
                <div>{{ msg|raw }}</div>
               <p>Vous pouvez imprimer ou sauvegarder ce message de réservation en cliquant sur le bouton "Enregistrer mon détail".</p>
            {% endfor %}
        {% endfor %}
        </div>

        <div class="detailresa">
            <ul><br><br>
                <li> Date d'arrivée :          {{ reservation.dateArrivee|date('d/m/y') }}</li><br>
                <li> Date du départ :          {{ reservation.dateDepart|date('d/m/y') }}</li><br>
                <li> Nombre de personne(s) :   {{ reservation.nombrePersonnes }}</li><br>
                <li> Type de chambre :         {{ reservation.chambre.typeChambre}}</li><br>
                <li> Nombre d'animal/animaux : {{ reservation.nombreAnimaux }}</li><br>
                <li> Type d'animal/animaux :   {{ reservation.typeAnimaux }}</li><br>
             </ul>
        </div>   

        <div class="message">
        <p> Nous informons notre aimable clientèle, que toute annulation se fera via le formulaire de contact ou par téléphone.</p>
        
        </div>
        
            <h2>Récapitulatif des tarifs</h2>
            <div class="trait"></div>
         <section id="Recaptarif">
               <div class="infostarifs">
                    <h3>Petit déjeuner<br><br></h3>
                    <i class="fas fa-mug-hot" id="icone"></i><br>
                    <li> inclus dans le tarif des chambres</li><br>
                </div>

                <div class="infostarifs">
                    <h3>Tarifs animaux<br><br></h3>
                    <i class="fas fa-cat" id="icone"></i>
                    <i class="fas fa-dog" id="icone"></i><br>
                    <li> Par Animal 5 euros par jour en plus du prix de la chambre</li>
                    <li> Se renseigner à l'accueil pour le tarif du pet sitter</li><br>
                </div>

                <div class="infostarifs">
                    <h3>Tarifs de nos chambres<br><br></h3>
                    <i class="fas fa-bed" id="icone"></i><br>
                   <li> Chambre simple 50 euros la nuit</li>
                    <li> Chambre double 100 euros la nuit</li>
                    <li> Chambre triple 150 euros la nuit</li>
                </div>
                <div class="infostarifs">
                    <h3>Tarifs soins<br><br></h3>
                    <i class="fas fa-hot-tub" id="icone"></i><br>
                    <li> Massages : 30€ la scéance de 45 min</li>
                    <li> Hammam et sauna : 20€ les 30 min</li>
                    <li> Piscine incluse dans le tarif des chambres</li>
                </div>
                </section>
            <img src="{{ asset('asset/img/logocarte.jpg')}}" alt="logo paiement" id="carte">



{% endblock %}

templates/resa_client/new.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
{{ parent() }}
<link rel="stylesheet" href="{{ asset('asset/css/resa_client.css')}}">
{% endblock %}
{% block body %}
<h1>Réservation</h1>
<div class="trait"></div>
<h1 id="bonjour">Bonjour , {{ app.user.nom}} {{ app.user.prenom}}</h1>
<p id="pararesa"> Veuillez compléter les champs du formulaire ci-dessous, afin de rendre effective votre réservation.</p>

<div class="fondResa">

{{ form_start(form) }}
<section class="resa">
    <div>
    {{ form_row(form.date_arrivee)}}
    {{ form_row(form.nombre_personnes)}}
    {{ form_row(form.nombre_animaux)}}

    </div>
    <div>
    {{ form_row(form.date_depart)}}
    {{ form_row(form.chambre)}}
    {{ form_row(form.type_animaux)}}

    </div>
    </section>
<button class="btn">{{ button_label|default('Réserver') }}</button>

</div>




{{ form_end(form) }}


{% for chambre in chambres %}


                <section class="cardResa">
    <h3>Chambre  {{ chambre.typeChambre }}</h3>

    <div class="sousCard">
    <img src="{{dossier_images ~ chambre.photo}}" alt="">
    <div class="sousDetail">
    <p> Cette chambre accepte les animaux : <strong class="yesno">{{ chambre.accepteAnimaux }}</strong></p>
    <p>{{ chambre.detail }}</p>
    <p> <i class="fas fa-wifi"></i> Wifi gratuit<br>
        <i class="fas fa-luggage-cart"></i> Conciergerie </p>
    </div>
     {% if reservationsfaites is defined %}
             {% if reservation not in reservationsfaites %}
                <i class="fa fa-cart-arrow-down"></i> Disponible
             {% else %}
                <i class="fa fa-times"></i> Indisponible 
            {% endif %}
    {% endif %}

    <p id="tarif"><strong>Tarif : {{ chambre.prix }} €</strong></p>
</div>


</section>
{% endfor %}

{% endblock %}