src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChambreRepository::class)
 */
class Chambre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $type_chambre;

   

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $disponibilite;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $accepte_animaux;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2)
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $detail;

    /**
     * @ORM\Column(type="integer")
     */
    private $num_chambre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="chambre")
     */
    private $reservations;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeChambre(): ?string
    {
        return $this->type_chambre;
    }

    public function setTypeChambre(string $type_chambre): self
    {
        $this->type_chambre = $type_chambre;

        return $this;
    }



    public function getDisponibilite(): ?string
    {
        return $this->disponibilite;
    }

    public function setDisponibilite(string $disponibilite): self
    {
        $this->disponibilite = $disponibilite;

        return $this;
    }

    public function getAccepteAnimaux(): ?string
    {
        return $this->accepte_animaux;
    }

    public function setAccepteAnimaux(string $accepte_animaux): self
    {
        $this->accepte_animaux = $accepte_animaux;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): self
    {
        $this->detail = $detail;

        return $this;
    }

    public function getNumChambre(): ?int
    {
        return $this->num_chambre;
    }

    public function setNumChambre(int $num_chambre): self
    {
        $this->num_chambre = $num_chambre;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setChambre($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getChambre() === $this) {
                $reservation->setChambre(null);
            }
        }

        return $this;
    }
}

src/Form/ChambreType.php
<?php

namespace App\Form;

use App\Entity\Chambre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChambreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('type_chambre')
            ->add('num_chambre')
            ->add('photo', FileType::class, [
                "mapped"=> false,
            ])
            ->add('disponibilite', ChoiceType::class, [
                'choices' => [
                    'oui'=> 'oui','non' => 'non', 
                ],
                "expanded" => false,
                "multiple" => false,

            ])
            ->add('accepte_animaux', ChoiceType::class, [
                'choices' => [
                    'oui'=> 'oui','non' => 'non', 
                ],
                "expanded" => false,
                "multiple" => false,

            ])
            ->add('prix')
            ->add('detail')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Chambre::class,
        ]);
    }
}

src/Controller/ChambreController.php
<?php

namespace App\Controller;

use App\Entity\Chambre;
use App\Form\ChambreType;
use App\Repository\ChambreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/chambre')]
class ChambreController extends AbstractController
{
    #[Route('/', name: 'chambre_index', methods: ['GET'])]
    public function index(ChambreRepository $chambreRepository): Response
    {
        return $this->render('chambre/index.html.twig', [
            'chambres' => $chambreRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'chambre_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $chambre = new Chambre();
        $form = $this->createForm(ChambreType::class, $chambre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if( $fichier = $form->get("photo")->getData() ){

                $nomFichier = pathinfo($fichier->getClientOriginalName(), PATHINFO_FILENAME); 
                $nomFichier = str_replace(" ", "_", $nomFichier);
                $nomFichier .= uniqid() . "." . $fichier->guessExtension();
                $fichier->move($this->getParameter( "dossier_images" ), $nomFichier);
                $chambre->setPhoto($nomFichier);
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($chambre);
            $entityManager->flush();

            return $this->redirectToRoute('chambre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('chambre/new.html.twig', [
            'chambre' => $chambre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'chambre_show', methods: ['GET'])]
    public function show(Chambre $chambre): Response
    {
        return $this->render('chambre/show.html.twig', [
            'chambre' => $chambre,
        ]);
    }

    #[Route('/{id}/edit', name: 'chambre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Chambre $chambre): Response
    {
        $form = $this->createForm(ChambreType::class, $chambre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if( $fichier = $form->get("photo")->getData() ){

                $nomFichier = pathinfo($fichier->getClientOriginalName(), PATHINFO_FILENAME); 
                $nomFichier = str_replace(" ", "_", $nomFichier);
                $nomFichier .= uniqid() . "." . $fichier->guessExtension();
                $fichier->move($this->getParameter( "dossier_images" ), $nomFichier);
                $chambre->setPhoto($nomFichier);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('chambre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('chambre/edit.html.twig', [
            'chambre' => $chambre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'chambre_delete', methods: ['POST'])]
    public function delete(Request $request, Chambre $chambre): Response
    {
        if ($this->isCsrfTokenValid('delete'.$chambre->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($chambre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('chambre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/chambre/_delete_form.html.twig
<form method="post" action="{{ path('chambre_delete', {'id': chambre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ chambre.id) }}">
    <button class="btnDelete">Effacer</button>
</form>

templates/chambre/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/chambre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Chambre{% endblock %}

{% block body %}
    <h1>Modifier une Chambre</h1>
    <div class="trait"></div>
    <a href="{{ path('chambre_index') }}"><i class="fas fa-undo-alt" id="return"></i></a>
    


    {{ include('chambre/_form.html.twig', {'button_label': 'Modifier'}) }}
    {{ include('chambre/_delete_form.html.twig') }}


{% endblock %}

templates/chambre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chambres{% endblock %}

{% block body %}
    <h1>Liste des chambres</h1>
    <div class="trait"></div>
  <a href="{{ path('chambre_new') }}"><button>Créer</button></a>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Photo</th>
                <th>Type de chambre</th>
                <th>N° de chambre</th>
                <th>Disponibilite</th>
                <th>Accepte les animaux</th>
                <th>Prix</th>
                <th>Détails</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for chambre in chambres %}
            <tr>
                <td>{{ chambre.id }}</td>
                <td><img src="{{ dossier_images ~ chambre.photo }}"></td>
                <td>{{ chambre.typeChambre }}</td>
                <td>{{ chambre.numChambre }}</td>
                <td>{{ chambre.disponibilite }}</td>
                <td>{{ chambre.accepteAnimaux }}</td>
                <td>{{ chambre.prix }}</td>
                <td>{{ chambre.detail }}</td>
                <td>
                    <a href="{{ path('chambre_show', {'id': chambre.id}) }}"><i class="fas fa-eye"></i></a>
                    <a href="{{ path('chambre_edit', {'id': chambre.id}) }}"><i class="fas fa-pencil-alt"></i></a>
                </td>
            </tr>

        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

     

  
{% endblock %}

templates/chambre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Chambre{% endblock %}

{% block body %}
    <h1>Créer une nouvelle Chambre</h1>
    <div class="trait"></div>
    <a href="{{ path('chambre_index') }}">Retour à la liste</a>

    {{ include('chambre/_form.html.twig') }}

{% endblock %}

templates/chambre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chambre{% endblock %}

{% block body %}
    <h1>Voir la chambre</h1>
    <div class="trait"></div>

    <a href="{{ path('chambre_index') }}"><i class="fas fa-undo-alt" id="return"></i></a>
    <a href="{{ path('chambre_edit', {'id': chambre.id}) }}"><button class="btnModif">Modifier</button></a>

<table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <th>Photo</th>

            </tr>
            <tr>
                <td>{{ chambre.id }}</td>
                <td><img src="{{ dossier_images ~ chambre.photo }}"></td>
            </tr>
            <tr>
                <th>Type de chambre</th>
                <td>{{ chambre.typeChambre }}</td>
            </tr>

            <tr>
                <th>N° de chambre</th>
                <td>{{ chambre.numChambre }}</td>
            </tr>
            <tr>
                <th>Disponibilité</th>
                <td>{{ chambre.disponibilite }}</td>
            </tr>
            <tr>
                <th>Accepte les animaux</th>
                <td>{{ chambre.accepteAnimaux }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ chambre.prix }}</td>
            </tr>
            <tr>
                <th>Détails</th>
                <td>{{ chambre.detail }}</td>
            </tr>
        </tbody>
    </table>


{{ include('chambre/_delete_form.html.twig') }}



{% endblock %}